Repository HERE-TRILLIONAIRES/try-and-review, pull requests merged in 2025-01, with the labels that each got.

#3 chore : issue, pr template 생성
  .github/ISSUE_TEMPLATE/feature_request.md
  pull_request_template.md
Labels: documentation

#5 [Feat/docker-compose] Docker-compose 작성
  .gitmodules
  .idea/.gitignore
  docker-compose.yml
  loki/loki-config.yml
  prometheus/prometheus.yml
Labels: documentation

#9 [Feat/product] 상품 등록 API 개발
  com.trillionares.tryit.product/build.gradle
  com.trillionares.tryit.product/src/main/java/com/trillionares/tryit/product/ProductApplication.java
  com.trillionares.tryit.product/src/main/java/com/trillionares/tryit/product/domain/common/base/BaseEntity.java
  com.trillionares.tryit.product/src/main/java/com/trillionares/tryit/product/domain/model/product/Product.java
  com.trillionares.tryit.product/src/main/java/com/trillionares/tryit/product/domain/repository/ProductRepository.java
  com.trillionares.tryit.product/src/main/java/com/trillionares/tryit/product/domain/service/ProductService.java
  com.trillionares.tryit.product/src/main/java/com/trillionares/tryit/product/infrastructure/config/JpaConfig.java
  com.trillionares.tryit.product/src/main/java/com/trillionares/tryit/product/presentation/controller/ProductController.java
  com.trillionares.tryit.product/src/main/java/com/trillionares/tryit/product/presentation/dto/BaseResponseDto.java
  com.trillionares.tryit.product/src/main/java/com/trillionares/tryit/product/presentation/dto/ProductIdResponseDto.java
  com.trillionares.tryit.product/src/main/java/com/trillionares/tryit/product/presentation/dto/ProductInfoRequestDto.java
  com.trillionares.tryit.product/src/main/resources/application.yml
Labels: feature

#34 [feat/handle-exception] 공통 예외 처리 부분 구현
  com.trillionares.tryit.config/build.gradle
  com.trillionares.tryit.config/src/main/resources/application.yml
  com.trillionares.tryit.config/src/main/resources/config-repo/notification-service.yml
  com.trillionares.tryit.notification/build.gradle
  com.trillionares.tryit.notification/src/main/java/com/trillionares/tryit/notification/libs/exception/ErrorCode.java
  com.trillionares.tryit.notification/src/main/java/com/trillionares/tryit/notification/libs/exception/ErrorResponse.java
  com.trillionares.tryit.notification/src/main/java/com/trillionares/tryit/notification/libs/exception/ExceptionConverter.java
  com.trillionares.tryit.notification/src/main/java/com/trillionares/tryit/notification/libs/exception/GlobalException.java
  com.trillionares.tryit.notification/src/main/java/com/trillionares/tryit/notification/libs/exception/GlobalExceptionHandler.java
Labels: feature

#30 [Feat/review-setting] 리뷰 기본 클래스 생성
  com.trillionares.tryit.review/build.gradle
  com.trillionares.tryit.review/src/main/java/com/trillionares/tryit/review/ReviewApplication.java
  com.trillionares.tryit.review/src/main/java/com/trillionares/tryit/review/domain/common/base/BaseEntity.java
  com.trillionares.tryit.review/src/main/java/com/trillionares/tryit/review/domain/model/Review.java
  com.trillionares.tryit.review/src/main/resources/application.yml
Labels: feature

#31 [Feat/statistics-setting] 통계 기본 클래스 생성
  com.trillionares.tryit.statistics/build.gradle
  com.trillionares.tryit.statistics/src/main/java/com/trillionares/tryit/statistics/StatisticsApplication.java
  com.trillionares.tryit.statistics/src/main/java/com/trillionares/tryit/statistics/domain/common/base/BaseEntity.java
  com.trillionares.tryit.statistics/src/main/java/com/trillionares/tryit/statistics/domain/model/Statistics.java
  com.trillionares.tryit.statistics/src/main/resources/application.yml
Labels: feature

#51 [Feat/Recruitment]: 체험단 모집 서비스 및 관련 기능 구현
  com.trillionares.tryit.product/build.gradle
  com.trillionares.tryit.product/src/main/java/com/trillionares/tryit/product/recruitment/application/service/RecruitmentService.java
  com.trillionares.tryit.product/src/main/java/com/trillionares/tryit/product/recruitment/domain/model/Recruitment.java
  com.trillionares.tryit.product/src/main/java/com/trillionares/tryit/product/recruitment/domain/model/type/RecruitmentStatus.java
  com.trillionares.tryit.product/src/main/java/com/trillionares/tryit/product/recruitment/domain/repository/RecruitmentRepository.java
  com.trillionares.tryit.product/src/main/java/com/trillionares/tryit/product/recruitment/presentation/controller/RecruitmentController.java
  com.trillionares.tryit.product/src/main/java/com/trillionares/tryit/product/recruitment/presentation/dto/request/CreateRecruitmentRequest.java
  com.trillionares.tryit.product/src/main/java/com/trillionares/tryit/product/recruitment/presentation/dto/request/UpdateRecruitmentRequest.java
  com.trillionares.tryit.product/src/main/java/com/trillionares/tryit/product/recruitment/presentation/dto/request/UpdateRecruitmentStatusRequest.java
  com.trillionares.tryit.product/src/main/java/com/trillionares/tryit/product/recruitment/presentation/dto/response/GetRecruitmentResponse.java
  com.trillionares.tryit.product/src/main/java/com/trillionares/tryit/product/recruitment/presentation/dto/response/RecruitmentIdResponse.java
  com.trillionares.tryit.product/src/main/java/com/trillionares/tryit/product/recruitment/presentation/dto/response/UpdateRecruitmentStatusResponse.java
Labels: feature

#41 [Feat/review-delete] 리뷰 삭제 API 개발
  com.trillionares.tryit.review/src/main/java/com/trillionares/tryit/review/application/dto/response/ReviewDeleteResponseDto.java
  com.trillionares.tryit.review/src/main/java/com/trillionares/tryit/review/application/service/ReviewService.java
  com.trillionares.tryit.review/src/main/java/com/trillionares/tryit/review/domain/common/base/BaseEntity.java
  com.trillionares.tryit.review/src/main/java/com/trillionares/tryit/review/domain/repository/ReviewRepository.java
  com.trillionares.tryit.review/src/main/java/com/trillionares/tryit/review/presentation/controller/ReviewController.java
Labels: feature

#50 [Feat/user-create] 회원가입 및 로그인 API 개발
  com.trillionares.tryit.auth/build.gradle
  com.trillionares.tryit.auth/src/main/java/com/trillionares/tryit/auth/AuthApplication.java
  com.trillionares.tryit.auth/src/main/java/com/trillionares/tryit/auth/application/dto/UserAuthorityResponseDto.java
  com.trillionares.tryit.auth/src/main/java/com/trillionares/tryit/auth/application/service/AuthService.java
  com.trillionares.tryit.auth/src/main/java/com/trillionares/tryit/auth/application/service/UserService.java
  com.trillionares.tryit.auth/src/main/java/com/trillionares/tryit/auth/domain/common/base/BaseEntity.java
  com.trillionares.tryit.auth/src/main/java/com/trillionares/tryit/auth/domain/model/Role.java
  com.trillionares.tryit.auth/src/main/java/com/trillionares/tryit/auth/domain/model/User.java
  com.trillionares.tryit.auth/src/main/java/com/trillionares/tryit/auth/domain/repository/UserRepository.java
  com.trillionares.tryit.auth/src/main/java/com/trillionares/tryit/auth/infrastructure/config/AuditorAwareImpl.java
  com.trillionares.tryit.auth/src/main/java/com/trillionares/tryit/auth/infrastructure/config/CustomAuthenticationProvider.java
  com.trillionares.tryit.auth/src/main/java/com/trillionares/tryit/auth/infrastructure/config/CustomUserDetails.java
  com.trillionares.tryit.auth/src/main/java/com/trillionares/tryit/auth/infrastructure/config/CustomUserDetailsService.java
  com.trillionares.tryit.auth/src/main/java/com/trillionares/tryit/auth/infrastructure/config/JpaConfig.java
  com.trillionares.tryit.auth/src/main/java/com/trillionares/tryit/auth/infrastructure/config/SecurityConfig.java
  com.trillionares.tryit.auth/src/main/java/com/trillionares/tryit/auth/infrastructure/config/jwt/JwtUtil.java
  com.trillionares.tryit.auth/src/main/java/com/trillionares/tryit/auth/infrastructure/config/jwt/SecretKeyGenerator.java
  com.trillionares.tryit.auth/src/main/java/com/trillionares/tryit/auth/infrastructure/config/jwt/filter/JwtAuthorizationFilter.java
  com.trillionares.tryit.auth/src/main/java/com/trillionares/tryit/auth/infrastructure/config/jwt/filter/LoginFilter.java
  com.trillionares.tryit.auth/src/main/java/com/trillionares/tryit/auth/libs/exception/ErrorCode.java
  com.trillionares.tryit.auth/src/main/java/com/trillionares/tryit/auth/libs/exception/ErrorResponse.java
  com.trillionares.tryit.auth/src/main/java/com/trillionares/tryit/auth/libs/exception/ExceptionConverter.java
  com.trillionares.tryit.auth/src/main/java/com/trillionares/tryit/auth/libs/exception/GlobalException.java
  com.trillionares.tryit.auth/src/main/java/com/trillionares/tryit/auth/libs/exception/GlobalExceptionHandler.java
  com.trillionares.tryit.auth/src/main/java/com/trillionares/tryit/auth/presentation/controller/UserController.java
  com.trillionares.tryit.auth/src/main/java/com/trillionares/tryit/auth/presentation/dto/BaseResponse.java
  com.trillionares.tryit.auth/src/main/java/com/trillionares/tryit/auth/presentation/dto/requestDto/PasswordUpdateReqDto.java
  com.trillionares.tryit.auth/src/main/java/com/trillionares/tryit/auth/presentation/dto/requestDto/SignInRequestDto.java
  com.trillionares.tryit.auth/src/main/java/com/trillionares/tryit/auth/presentation/dto/requestDto/SignUpRequestDto.java
  com.trillionares.tryit.auth/src/main/java/com/trillionares/tryit/auth/presentation/dto/requestDto/UserInfoUpdateReqDto.java
  com.trillionares.tryit.auth/src/main/java/com/trillionares/tryit/auth/presentation/dto/responseDto/SignInResponseDto.java
  com.trillionares.tryit.auth/src/main/java/com/trillionares/tryit/auth/presentation/dto/responseDto/UserResponseDto.java
  com.trillionares.tryit.auth/src/main/resources/application.yml
Labels: feature

#60 [Feat/statistics-create] 통계 생성 API 개발
  com.trillionares.tryit.statistics/src/main/java/com/trillionares/tryit/statistics/application/dto/request/StatisticsCreateRequestDto.java
  com.trillionares.tryit.statistics/src/main/java/com/trillionares/tryit/statistics/application/dto/response/StatisticsCreateResponseDto.java
  com.trillionares.tryit.statistics/src/main/java/com/trillionares/tryit/statistics/application/service/StatisticsService.java
  com.trillionares.tryit.statistics/src/main/java/com/trillionares/tryit/statistics/domain/common/base/BaseEntity.java
  com.trillionares.tryit.statistics/src/main/java/com/trillionares/tryit/statistics/domain/model/Statistics.java
  com.trillionares.tryit.statistics/src/main/java/com/trillionares/tryit/statistics/domain/respository/StatisticsRepository.java
  com.trillionares.tryit.statistics/src/main/java/com/trillionares/tryit/statistics/infrastructure/persistence/StatisticsRepositoryImpl.java
  com.trillionares.tryit.statistics/src/main/java/com/trillionares/tryit/statistics/presentation/controller/StatisticsController.java
  com.trillionares.tryit.statistics/src/main/java/com/trillionares/tryit/statistics/presentation/dto/BaseResponse.java
  com.trillionares.tryit.statistics/src/main/java/com/trillionares/tryit/statistics/presentation/dto/StatisticsCreateRequest.java
Labels: feature

#78 [Feat/trial-kafka] 상품 생성 API - 이미지 DB 저장시 kafka 활용
  .gitignore
  com.trillionares.tryit.image-manage/build.gradle
  com.trillionares.tryit.image-manage/src/main/java/com/trillionares/tryit/image_manage/domain/common/json/JsonUtils.java
  com.trillionares.tryit.image-manage/src/main/java/com/trillionares/tryit/image_manage/domain/service/ImageEndpoint.java
  com.trillionares.tryit.image-manage/src/main/java/com/trillionares/tryit/image_manage/infrastructure/messaging/kafka/ConsumerApplicationKafkaConfig.java
  com.trillionares.tryit.image-manage/src/main/java/com/trillionares/tryit/image_manage/infrastructure/messaging/kafka/ProducerApplicationKafkaConfig.java
  com.trillionares.tryit.image-manage/src/main/java/com/trillionares/tryit/image_manage/presentation/dto/ProductIdAndProductImageIdDto.java
  com.trillionares.tryit.image-manage/src/main/resources/application.yml
  com.trillionares.tryit.product/build.gradle
  com.trillionares.tryit.product/src/main/java/com/trillionares/tryit/product/application/service/ProductEndpoint.java
  com.trillionares.tryit.product/src/main/java/com/trillionares/tryit/product/application/service/ProductService.java
  com.trillionares.tryit.product/src/main/java/com/trillionares/tryit/product/application/service/RecruitmentEndpoint.java
  com.trillionares.tryit.product/src/main/java/com/trillionares/tryit/product/infrastructure/messaging/kafka/ConsumerApplicationKafkaConfig.java
  com.trillionares.tryit.product/src/main/java/com/trillionares/tryit/product/infrastructure/messaging/kafka/ProducerApplicationKafkaConfig.java
  com.trillionares.tryit.product/src/main/java/com/trillionares/tryit/product/presentation/controller/CategoryController.java
  com.trillionares.tryit.product/src/main/java/com/trillionares/tryit/product/presentation/controller/ProductController.java
  com.trillionares.tryit.product/src/main/java/com/trillionares/tryit/product/presentation/dto/ProductIdAndProductImageIdDto.java
  com.trillionares.tryit.product/src/main/java/com/trillionares/tryit/product/presentation/dto/common/base/BaseResponseDto.java
  com.trillionares.tryit.product/src/main/resources/application.yml
  com.trillionares.tryit.product/src/test/java/com/trillionares/tryit/product/application/service/ProductServiceTest.java
  com.trillionares.tryit.product/src/test/resources/application-test.yml
  com.trillionares.tryit.trial/build.gradle
  com.trillionares.tryit.trial/src/main/java/com/trillionares/tryit/trial/jhtest/domain/common/json/JsonUtils.java
  com.trillionares.tryit.trial/src/main/java/com/trillionares/tryit/trial/jhtest/domain/model/Trial.java
  com.trillionares.tryit.trial/src/main/java/com/trillionares/tryit/trial/jhtest/domain/model/type/SubmissionStatus.java
  com.trillionares.tryit.trial/src/main/java/com/trillionares/tryit/trial/jhtest/domain/repository/TrialRepository.java
  com.trillionares.tryit.trial/src/main/java/com/trillionares/tryit/trial/jhtest/domain/service/TrialService.java
  com.trillionares.tryit.trial/src/main/java/com/trillionares/tryit/trial/jhtest/infrastructure/config/JpaConfig.java
  com.trillionares.tryit.trial/src/main/java/com/trillionares/tryit/trial/jhtest/infrastructure/messaging/kafka/ProducerApplicationKafkaConfig.java
  com.trillionares.tryit.trial/src/main/java/com/trillionares/tryit/trial/jhtest/presentation/controller/trialController.java
  com.trillionares.tryit.trial/src/main/java/com/trillionares/tryit/trial/jhtest/presentation/dto/SendNotificationDto.java
  com.trillionares.tryit.trial/src/main/java/com/trillionares/tryit/trial/jhtest/presentation/dto/common/kafka/KafkaMessage.java
  com.trillionares.tryit.trial/src/main/resources/application.yml
Labels: feature

#89 [Feat/trial-kafka-bug] 체험단 신청시 - Kafka 비동기 통신 연동 bug fix
  com.trillionares.tryit.trial/src/main/java/com/trillionares/tryit/trial/jhtest/domain/service/TrialService.java
  com.trillionares.tryit.trial/src/main/java/com/trillionares/tryit/trial/jhtest/presentation/dto/SendNotificationDto.java
  com.trillionares.tryit.trial/src/main/java/com/trillionares/tryit/trial/jhtest/presentation/dto/common/kafka/KafkaMessage.java
Labels: bug

#84 [Feat/statistics-validation] 통계 검증 및 예외처리
  com.trillionares.tryit.statistics/build.gradle
  com.trillionares.tryit.statistics/src/main/java/com/trillionares/tryit/statistics/libs/exception/ErrorCode.java
  com.trillionares.tryit.statistics/src/main/java/com/trillionares/tryit/statistics/libs/exception/ErrorResponse.java
  com.trillionares.tryit.statistics/src/main/java/com/trillionares/tryit/statistics/libs/exception/ExceptionConverter.java
  com.trillionares.tryit.statistics/src/main/java/com/trillionares/tryit/statistics/libs/exception/GlobalException.java
  com.trillionares.tryit.statistics/src/main/java/com/trillionares/tryit/statistics/libs/exception/GlobalExceptionHandler.java
  com.trillionares.tryit.statistics/src/main/java/com/trillionares/tryit/statistics/presentation/controller/StatisticsController.java
  com.trillionares.tryit.statistics/src/main/java/com/trillionares/tryit/statistics/presentation/dto/StatisticsCreateRequest.java
Labels: feature

#82 [Feat/review-validation] 리뷰 검증 및 예외처리
  com.trillionares.tryit.review/build.gradle
  com.trillionares.tryit.review/src/main/java/com/trillionares/tryit/review/application/service/ReviewService.java
  com.trillionares.tryit.review/src/main/java/com/trillionares/tryit/review/libs/exception/ErrorCode.java
  com.trillionares.tryit.review/src/main/java/com/trillionares/tryit/review/libs/exception/ErrorResponse.java
  com.trillionares.tryit.review/src/main/java/com/trillionares/tryit/review/libs/exception/ExceptionConverter.java
  com.trillionares.tryit.review/src/main/java/com/trillionares/tryit/review/libs/exception/GlobalException.java
  com.trillionares.tryit.review/src/main/java/com/trillionares/tryit/review/libs/exception/GlobalExceptionHandler.java
  com.trillionares.tryit.review/src/main/java/com/trillionares/tryit/review/presentation/controller/ReviewController.java
  com.trillionares.tryit.review/src/main/java/com/trillionares/tryit/review/presentation/dto/ReviewCreateRequest.java
  com.trillionares.tryit.review/src/main/java/com/trillionares/tryit/review/presentation/dto/ReviewUpdateRequest.java
Labels: feature

#93 [Fix/review-statistics-setting] config server 설정 테스트
  com.trillionares.tryit.statistics/src/main/resources/application.yml
Labels: bug

#91 [Feat/add kafka error] 사용자 통신 부분 추가
  com.trillionares.tryit.config/src/main/resources/config-repo/notification-service.yml
  com.trillionares.tryit.notification/build.gradle
  com.trillionares.tryit.notification/src/main/java/com/trillionares/tryit/notification/NotificationApplication.java
  com.trillionares.tryit.notification/src/main/java/com/trillionares/tryit/notification/application/service/NotificationService.java
  com.trillionares.tryit.notification/src/main/java/com/trillionares/tryit/notification/application/service/SlackNotificationSender.java
  com.trillionares.tryit.notification/src/main/java/com/trillionares/tryit/notification/domain/repository/NotificationRepository.java
  com.trillionares.tryit.notification/src/main/java/com/trillionares/tryit/notification/infrastructure/messaging/event/SubmissionEventConsumer.java
  com.trillionares.tryit.notification/src/main/java/com/trillionares/tryit/notification/infrastructure/messaging/event/SubmissionSelectedEvent.java
  com.trillionares.tryit.notification/src/main/java/com/trillionares/tryit/notification/infrastructure/messaging/kafka/NotificationTopic.java
  com.trillionares.tryit.notification/src/main/java/com/trillionares/tryit/notification/infrastructure/persistence/JpaNotificationRepository.java
  com.trillionares.tryit.notification/src/main/java/com/trillionares/tryit/notification/libs/client/auth/AuthServiceClient.java
  com.trillionares.tryit.notification/src/main/java/com/trillionares/tryit/notification/libs/client/auth/RequestHeaderProvider.java
  com.trillionares.tryit.notification/src/main/java/com/trillionares/tryit/notification/libs/client/auth/UserResponseDto.java
  com.trillionares.tryit.notification/src/main/java/com/trillionares/tryit/notification/libs/exception/ErrorCode.java
  com.trillionares.tryit.notification/src/main/java/com/trillionares/tryit/notification/libs/exception/GlobalExceptionHandler.java
  com.trillionares.tryit.notification/src/main/java/com/trillionares/tryit/notification/presentation/controller/NotificationController.java
  com.trillionares.tryit.notification/src/main/resources/application.yml
  com.trillionares.tryit.notification/src/test/http/notification.http
  com.trillionares.tryit.notification/src/test/java/com/trillionares/tryit/notification/NotificationServiceTest.java
Labels: feature

#101 [Feat/trial-kafka] 체험단 모집에게 Message 전송을 위한 Producer 생성
  com.trillionares.tryit.trial/src/main/java/com/trillionares/tryit/trial/jhtest/domain/service/TrialService.java
  com.trillionares.tryit.trial/src/main/java/com/trillionares/tryit/trial/jhtest/presentation/dto/SendRecruitmentDto.java
Labels: feature

#105 [Feat/trial-kafka] 신청 상태 변경을 위한 consumer 생성
  com.trillionares.tryit.trial/src/main/java/com/trillionares/tryit/trial/jhtest/domain/service/TrialEndpoint.java
  com.trillionares.tryit.trial/src/main/java/com/trillionares/tryit/trial/jhtest/domain/service/TrialService.java
  com.trillionares.tryit.trial/src/main/java/com/trillionares/tryit/trial/jhtest/infrastructure/messaging/kafka/ConsumerApplicationKafkaConfig.java
  com.trillionares.tryit.trial/src/main/java/com/trillionares/tryit/trial/jhtest/presentation/dto/SendNotificationDto.java
  com.trillionares.tryit.trial/src/main/java/com/trillionares/tryit/trial/jhtest/presentation/dto/UpdateStatusDto.java
Labels: feature

#112 [feat/trial-submitReview] feat: 리뷰제출시 '당첨 -> 리뷰 제출' 상태 업데이트 요청 endpoint
  com.trillionares.tryit.trial/src/main/java/com/trillionares/tryit/trial/jhtest/domain/service/TrialService.java
  com.trillionares.tryit.trial/src/main/java/com/trillionares/tryit/trial/jhtest/presentation/controller/trialController.java
Labels: feature

#110 feat: 모집 가능 여부 검증 및 Kafka 통신 로직 구현
  com.trillionares.tryit.product/src/main/java/com/trillionares/tryit/product/application/service/RecruitmentEndpoint.java
  com.trillionares.tryit.product/src/main/java/com/trillionares/tryit/product/application/service/RecruitmentService.java
  com.trillionares.tryit.product/src/main/java/com/trillionares/tryit/product/domain/model/recruitment/Recruitment.java
  com.trillionares.tryit.product/src/main/java/com/trillionares/tryit/product/presentation/dto/common/kafka/KafkaMessage.java
  com.trillionares.tryit.product/src/main/java/com/trillionares/tryit/product/presentation/dto/common/kafka/RecruitmentSubmissionResponseDto.java
  com.trillionares.tryit.product/src/main/java/com/trillionares/tryit/product/presentation/dto/common/kafka/SubmissionToRecruitmentRequestDto.java
Labels: feature

#102 [Feat/add notification test] 알림 조회 관련 오류 수정
  com.trillionares.tryit.notification/src/main/java/com/trillionares/tryit/notification/application/dto/NotificationResponse.java
  com.trillionares.tryit.notification/src/main/java/com/trillionares/tryit/notification/domain/common/base/BaseEntity.java
  com.trillionares.tryit.notification/src/main/java/com/trillionares/tryit/notification/infrastructure/config/JpaConfig.java
  com.trillionares.tryit.notification/src/main/java/com/trillionares/tryit/notification/libs/client/auth/AuthServiceClient.java
  com.trillionares.tryit.notification/src/main/java/com/trillionares/tryit/notification/libs/client/config/FeignClientConfig.java
  com.trillionares.tryit.notification/src/main/java/com/trillionares/tryit/notification/libs/client/config/RequestHeaderProvider.java
Labels: bug

#113 [Fix/auth feign client] 알림 - 사용자 조회부분, 슬랙 알림 송신 부분 개선
  com.trillionares.tryit.notification/src/main/java/com/trillionares/tryit/notification/application/dto/slack/SlackMessage.java
  com.trillionares.tryit.notification/src/main/java/com/trillionares/tryit/notification/application/service/NotificationService.java
  com.trillionares.tryit.notification/src/main/java/com/trillionares/tryit/notification/application/service/SlackNotificationSender.java
  com.trillionares.tryit.notification/src/main/java/com/trillionares/tryit/notification/libs/client/auth/AuthServiceClient.java
  com.trillionares.tryit.notification/src/main/java/com/trillionares/tryit/notification/libs/client/config/FeignClientConfig.java
  com.trillionares.tryit.notification/src/main/resources/application.yml
Labels: bug

#116 [Feat/review-create-contraints] 리뷰 작성 조건 로직 추가
  com.trillionares.tryit.review/build.gradle
  com.trillionares.tryit.review/src/main/java/com/trillionares/tryit/review/ReviewApplication.java
  com.trillionares.tryit.review/src/main/java/com/trillionares/tryit/review/application/dto/request/ReviewCreateRequestDto.java
  com.trillionares.tryit.review/src/main/java/com/trillionares/tryit/review/application/dto/response/ReviewIsSelectedResponseDto.java
  com.trillionares.tryit.review/src/main/java/com/trillionares/tryit/review/application/dto/response/ReviewSubmitResponseDto.java
  com.trillionares.tryit.review/src/main/java/com/trillionares/tryit/review/application/service/ReviewService.java
  com.trillionares.tryit.review/src/main/java/com/trillionares/tryit/review/domain/client/TrialClient.java
  com.trillionares.tryit.review/src/main/java/com/trillionares/tryit/review/libs/exception/ErrorCode.java
  com.trillionares.tryit.review/src/main/java/com/trillionares/tryit/review/presentation/dto/ReviewCreateRequest.java
Labels: feature

#115 [refactor/kafkamessage] refactor: kafka message 포맷 변경
  com.trillionares.tryit.product/src/main/java/com/trillionares/tryit/product/presentation/dto/common/kafka/KafkaMessage.java
  com.trillionares.tryit.trial/src/main/java/com/trillionares/tryit/trial/jhtest/domain/service/TrialService.java
  com.trillionares.tryit.trial/src/main/java/com/trillionares/tryit/trial/jhtest/presentation/dto/common/kafka/KafkaMessage.java
Labels: enhancement

#118 [docs/docker-compose] docs: Docker compose에 Zipkin 설정 추가
  docker-compose.yml
Labels: documentation

#120 [Feat/gateway] fix: 헤더값 못 받아오는 문제 해결
  com.trillionares.tryit.auth/src/main/java/com/trillionares/tryit/auth/infrastructure/config/jwt/JwtUtil.java
  com.trillionares.tryit.auth/src/main/java/com/trillionares/tryit/auth/presentation/controller/UserController.java
  com.trillionares.tryit.gateway/src/main/java/com/trillionares/tryit/gateway/config/GatewayConfig.java
  com.trillionares.tryit.gateway/src/main/java/com/trillionares/tryit/gateway/filter/JwtAuthFilter.java
  com.trillionares.tryit.gateway/src/main/java/com/trillionares/tryit/gateway/jwt/JwtUtil.java
  com.trillionares.tryit.gateway/src/main/resources/application.yml
Labels: bug

#123 [Feat/product-authorization] 상품 등록 CRUD & 카테고리 생성 권한 검증
  com.trillionares.tryit.product/src/main/java/com/trillionares/tryit/product/application/service/CategoryService.java
  com.trillionares.tryit.product/src/main/java/com/trillionares/tryit/product/application/service/ProductService.java
  com.trillionares.tryit.product/src/main/java/com/trillionares/tryit/product/domain/client/AuthClient.java
  com.trillionares.tryit.product/src/main/java/com/trillionares/tryit/product/presentation/controller/CategoryController.java
  com.trillionares.tryit.product/src/main/java/com/trillionares/tryit/product/presentation/controller/ProductController.java
  com.trillionares.tryit.product/src/main/java/com/trillionares/tryit/product/presentation/dto/InfoByUsernameResponseDto.java
  com.trillionares.tryit.product/src/main/java/com/trillionares/tryit/product/presentation/dto/UserResponseDto.java
Labels: feature

#129 [feat/trial-notification-status] fix: 체험단 신청 status 메시지 변경
  com.trillionares.tryit.trial/src/main/java/com/trillionares/tryit/trial/jhtest/domain/model/type/SubmissionStatus.java
Labels: bug

#128 feat: 모집 소유권 검증 및 사용자 권한 처리 로직 추가
  com.trillionares.tryit.product/src/main/java/com/trillionares/tryit/product/application/service/RecruitmentService.java
  com.trillionares.tryit.product/src/main/java/com/trillionares/tryit/product/domain/model/recruitment/Recruitment.java
  com.trillionares.tryit.product/src/main/java/com/trillionares/tryit/product/domain/repository/RecruitmentRepository.java
  com.trillionares.tryit.product/src/main/java/com/trillionares/tryit/product/presentation/controller/RecruitmentController.java
Labels: feature

#121 [Fix/fix kafka linkage] submission 연동 부분 오류 수정
  com.trillionares.tryit.config/src/main/resources/config-repo/notification-service.yml
  com.trillionares.tryit.notification/src/main/java/com/trillionares/tryit/notification/application/dto/slack/SlackNotificationSender.java
  com.trillionares.tryit.notification/src/main/java/com/trillionares/tryit/notification/application/service/NotificationService.java
  com.trillionares.tryit.notification/src/main/java/com/trillionares/tryit/notification/infrastructure/messaging/event/KafkaMessage.java
  com.trillionares.tryit.notification/src/main/java/com/trillionares/tryit/notification/infrastructure/messaging/event/SubmissionEventConsumer.java
  com.trillionares.tryit.notification/src/main/java/com/trillionares/tryit/notification/infrastructure/messaging/event/SubmissionKafkaEvent.java
  com.trillionares.tryit.notification/src/main/java/com/trillionares/tryit/notification/infrastructure/messaging/event/SubmissionSelectedEvent.java
  com.trillionares.tryit.notification/src/main/java/com/trillionares/tryit/notification/libs/client/auth/AuthServiceClient.java
  com.trillionares.tryit.notification/src/main/java/com/trillionares/tryit/notification/libs/client/config/InternalFeignClientConfig.java
  com.trillionares.tryit.notification/src/main/java/com/trillionares/tryit/notification/libs/client/config/RequestHeaderProvider.java
  com.trillionares.tryit.notification/src/main/java/com/trillionares/tryit/notification/libs/client/config/WebFeignClientConfig.java
  com.trillionares.tryit.notification/src/main/resources/application.yml
Labels: bug

#130 Bug: 체험단 신청 로직 에러 수정
  com.trillionares.tryit.notification/src/main/java/com/trillionares/tryit/notification/libs/client/auth/AuthServiceClient.java
  com.trillionares.tryit.notification/src/main/java/com/trillionares/tryit/notification/presentation/controller/NotificationController.java
  com.trillionares.tryit.trial/src/main/java/com/trillionares/tryit/trial/jhtest/domain/client/AuthClient.java
Labels: bug

#131 feat: 전체 서비스 config server 에 zipkin 설정 추가
  com.trillionares.tryit.auth/build.gradle
  com.trillionares.tryit.config/src/main/resources/config-repo/auth-service.yml
  com.trillionares.tryit.config/src/main/resources/config-repo/notification-service.yml
  com.trillionares.tryit.config/src/main/resources/config-repo/product-service.yml
  com.trillionares.tryit.config/src/main/resources/config-repo/review-service.yml
  com.trillionares.tryit.config/src/main/resources/config-repo/statistics-service.yml
  com.trillionares.tryit.config/src/main/resources/config-repo/trial-service.yml
  com.trillionares.tryit.notification/build.gradle
  com.trillionares.tryit.product/build.gradle
  com.trillionares.tryit.product/src/main/resources/application.yml
  com.trillionares.tryit.review/build.gradle
  com.trillionares.tryit.statistics/build.gradle
  com.trillionares.tryit.trial/build.gradle
  com.trillionares.tryit.trial/src/main/resources/application.yml
Labels: feature

#132 [Feat/review-role-validation] 리뷰 서비스 유저 권한 검증 추가
  com.trillionares.tryit.review/src/main/java/com/trillionares/tryit/review/application/dto/response/ReviewGetUserByUsernameResponseDto.java
  com.trillionares.tryit.review/src/main/java/com/trillionares/tryit/review/application/service/ReviewService.java
  com.trillionares.tryit.review/src/main/java/com/trillionares/tryit/review/domain/client/AuthClient.java
  com.trillionares.tryit.review/src/main/java/com/trillionares/tryit/review/domain/service/ReviewValidation.java
  com.trillionares.tryit.review/src/main/java/com/trillionares/tryit/review/libs/exception/ErrorCode.java
  com.trillionares.tryit.review/src/main/java/com/trillionares/tryit/review/presentation/controller/ReviewController.java
Labels: feature

#135 :memo: docs: Create aws.yml - trial-service
  .github/workflows/aws.yml
Labels: documentation

#136 :memo: add: revision file
  .github/workflows/trial-task-revision1.json
Labels: documentation

#137 :memo: docs: Update aws.yml
  .github/workflows/aws.yml
Labels: documentation

#138 :memo: docs: Update aws.yml
  .github/workflows/aws.yml
Labels: documentation

#139 :memo: docs: Update aws.yml
  .github/workflows/aws.yml
Labels: documentation

#141 :memo: docs: add dockerfile
  com.trillionares.tryit.auth/Dockerfile
  com.trillionares.tryit.config/Dockerfile
  com.trillionares.tryit.gateway/Dockerfile
  com.trillionares.tryit.image-manage/Dockerfile
  com.trillionares.tryit.notification/Dockerfile
  com.trillionares.tryit.product/Dockerfile
  com.trillionares.tryit.review/Dockerfile
  com.trillionares.tryit.server/Dockerfile
  com.trillionares.tryit.statistics/Dockerfile
  com.trillionares.tryit.trial/Dockerfile
Labels: documentation

#143 :memo: docs: Update aws.yml
  .github/workflows/aws.yml
Labels: documentation

#153 :memo: docs: Create gateway-task-revision1.json
  .github/workflows/gateway-task-revision1.json
Labels: documentation

#144 :memo: docs: Update aws.yml
  .github/workflows/aws.yml
Labels: documentation

#145 :memo: docs: Create auth-task-revision1.json
  .github/workflows/auth-task-revision1.json
Labels: documentation

#146 :memo: docs: Create product-task-revision1.json
  .github/workflows/product-task-revision1.json
Labels: documentation

#147 :memo: docs: Create review-task-revision1.json
  .github/workflows/review-task-revision1.json
Labels: documentation

#148 :memo: docs: Create notification-task-revision1.json
  .github/workflows/notification-task-revision1.json
Labels: documentation

#149 :memo: docs: Create statistics-task-revision1.json
  .github/workflows/statistics-task-revision1.json
Labels: documentation

#150 :memo: docs: Create image-manage-task-revision1.json
  .github/workflows/image-manage-task-revision1.json
Labels: documentation

#151 :memo: docs: Create config-task-revision1.json
  .github/workflows/config-task-revision1.json
Labels: documentation

#152 :memo: docs: Create server-task-revision1.json
  .github/workflows/server-task-revision1.json
Labels: documentation

#154 :memo: docs: Update aws.yml (server, config, gateway, trial)
  .github/workflows/aws.yml
Labels: documentation

#155 :rotating_light: fix: Update aws.yml
  .github/workflows/aws.yml
Labels: bug, documentation

#156 :rotating_light: fix: Update aws.yml
  .github/workflows/aws.yml
Labels: bug, documentation

#157 :rotating_light: fix: Update aws.yml
  .github/workflows/aws.yml
Labels: bug, documentation

#158 :rotating_light: fix: Update server-task-revision1.json
  .github/workflows/server-task-revision1.json
Labels: bug, documentation

#159 :rotating_light: fix: Update server-task-revision1.json
  .github/workflows/server-task-revision1.json
Labels: bug, documentation

#160 :rotating_light: fix: Update server-task-revision1.json
  .github/workflows/server-task-revision1.json
Labels: bug, documentation

#162 :rotating_light: fix: Update aws.yml
  .github/workflows/aws.yml
Labels: bug, documentation

#166 :rotating_light: fix: Update aws.yml
  .github/workflows/aws.yml
Labels: bug, documentation

#167 [Feat/gatewat] fix: PathMatch로 경로 읽기 수정 및 관련 설정 빌드그래들에 추가
  com.trillionares.tryit.gateway/build.gradle
  com.trillionares.tryit.gateway/src/main/java/com/trillionares/tryit/gateway/filter/JwtAuthFilter.java
Labels: bug

#168 :rotating_light: fix: Update aws.yml
  .github/workflows/aws.yml
Labels: bug, documentation

#169 :rotating_light: fis: Update aws.yml
  .github/workflows/aws.yml
Labels: bug, documentation

#170 :rotating_light: fix: Update aws.yml
  .github/workflows/aws.yml
Labels: bug, documentation

#142 refactor : config 서버 환경변수 반영
  com.trillionares.tryit.config/src/main/resources/config-repo/notification-service.yml
  com.trillionares.tryit.notification/build.gradle
  com.trillionares.tryit.notification/src/main/resources/application.yml
Labels: enhancement

#172 :sparkles: test: Update aws.yml
  .github/workflows/aws.yml
Labels: documentation

#173 :sparkles: test: Update aws.yml
  .github/workflows/aws.yml
Labels: documentation

#174 [Deploy/setting] 배포를 위한 DNS 세팅
  com.trillionares.tryit.auth/src/main/resources/application.yml
  com.trillionares.tryit.config/src/main/resources/application.yml
  com.trillionares.tryit.config/src/main/resources/config-repo/image-manage-service.yml
  com.trillionares.tryit.gateway/src/main/resources/application.yml
  com.trillionares.tryit.image-manage/src/main/resources/application.yml
  com.trillionares.tryit.notification/src/main/resources/application.yml
  com.trillionares.tryit.product/src/main/resources/application.yml
  com.trillionares.tryit.review/src/main/resources/application.yml
  com.trillionares.tryit.statistics/src/main/resources/application.yml
  com.trillionares.tryit.trial/src/main/resources/application.yml
Labels: documentation

#176 :memo: docs: add dns_env
  .github/workflows/aws.yml
Labels: documentation

#177 :memo: test: Update aws.yml
  .github/workflows/aws.yml
Labels: documentation

#178 :memo: add env to config-service
  .github/workflows/aws.yml
Labels: documentation

#179 [Deploy/setting] deploy: 배포
  .github/workflows/aws.yml
  com.trillionares.tryit.auth/src/main/resources/application.yml
  com.trillionares.tryit.product/src/main/resources/application.yml
  com.trillionares.tryit.review/src/main/resources/application.yml
  com.trillionares.tryit.statistics/src/main/resources/application.yml
Labels: documentation, enhancement

#180 :memo: test:Update aws.yml
  .github/workflows/aws.yml
Labels: documentation

#181 :memo: test: Update aws.yml
  .github/workflows/aws.yml
Labels: documentation

#182 Update aws.yml
  .github/workflows/aws.yml
Labels: documentation

#183 Update aws.yml
  .github/workflows/aws.yml
Labels: documentation

#184 Update aws.yml
  .github/workflows/aws.yml
Labels: documentation

#185 Update aws.yml
  .github/workflows/aws.yml
Labels: documentation

#187 Update aws.yml
  .github/workflows/aws.yml
Labels: documentation

#188 Update aws.yml
  .github/workflows/aws.yml
Labels: documentation

#189 :sparkles: feat: add permitall '/actuator/health' for healthcheck
  com.trillionares.tryit.auth/src/main/java/com/trillionares/tryit/auth/infrastructure/config/SecurityConfig.java
Labels: bug, documentation

#190 Update aws.yml
  .github/workflows/aws.yml
Labels: documentation

#191 Update aws.yml
  .github/workflows/aws.yml
Labels: documentation

#192 Update aws.yml
  .github/workflows/aws.yml
Labels: documentation

#193 Update aws.yml
  .github/workflows/aws.yml
Labels: documentation

#194 :wrench: docs: add config dependency
  com.trillionares.tryit.image-manage/build.gradle
Labels: documentation

#195 :memo: docs: change deploy branch Update aws.yml
  .github/workflows/aws.yml
Labels: documentation

#196 [develop] Deploy 설정
  .github/workflows/aws.yml
  com.trillionares.tryit.gateway/src/main/java/com/trillionares/tryit/gateway/config/GatewayCorsConfig.java
  com.trillionares.tryit.gateway/src/main/resources/application.yml
Labels: documentation, feature

#197 [develop] Deploy : kafka 적용
  .github/workflows/aws.yml
  com.trillionares.tryit.config/src/main/resources/config-repo/notification-service.yml
  com.trillionares.tryit.gateway/src/main/java/com/trillionares/tryit/gateway/config/GatewayCorsConfig.java
  com.trillionares.tryit.gateway/src/main/resources/application.yml
  com.trillionares.tryit.image-manage/src/main/resources/application.yml
  com.trillionares.tryit.product/src/main/resources/application.yml
  com.trillionares.tryit.trial/src/main/resources/application.yml
Labels: documentation

#198 :recycle: docs: Register DNS when registering service in eureka
  com.trillionares.tryit.auth/src/main/resources/application.yml
  com.trillionares.tryit.config/src/main/resources/application.yml
  com.trillionares.tryit.gateway/src/main/resources/application.yml
  com.trillionares.tryit.image-manage/src/main/resources/application.yml
  com.trillionares.tryit.notification/src/main/resources/application.yml
  com.trillionares.tryit.product/src/main/resources/application.yml
  com.trillionares.tryit.review/src/main/resources/application.yml
  com.trillionares.tryit.statistics/src/main/resources/application.yml
  com.trillionares.tryit.trial/src/main/resources/application.yml
Labels: documentation

#201 Update aws.yml
  .github/workflows/aws.yml
Labels: documentation

#203 :recycle: docs: Register DNS when registering service in eureka
  com.trillionares.tryit.auth/src/main/resources/application.yml
  com.trillionares.tryit.config/src/main/resources/application.yml
  com.trillionares.tryit.gateway/src/main/resources/application.yml
  com.trillionares.tryit.image-manage/src/main/resources/application.yml
  com.trillionares.tryit.notification/src/main/resources/application.yml
  com.trillionares.tryit.product/src/main/resources/application.yml
  com.trillionares.tryit.review/src/main/resources/application.yml
  com.trillionares.tryit.statistics/src/main/resources/application.yml
  com.trillionares.tryit.trial/src/main/resources/application.yml
Labels: documentation

#204 :recycle: docs: Register DNS when registering service in eureka
  com.trillionares.tryit.auth/src/main/resources/application.yml
  com.trillionares.tryit.config/src/main/resources/application.yml
  com.trillionares.tryit.gateway/src/main/resources/application.yml
  com.trillionares.tryit.image-manage/src/main/resources/application.yml
  com.trillionares.tryit.notification/src/main/resources/application.yml
  com.trillionares.tryit.product/src/main/resources/application.yml
  com.trillionares.tryit.review/src/main/resources/application.yml
  com.trillionares.tryit.statistics/src/main/resources/application.yml
  com.trillionares.tryit.trial/src/main/resources/application.yml
Labels: documentation

#205 Update aws.yml
  .github/workflows/aws.yml
Labels: documentation

#206 Update aws.yml
  .github/workflows/aws.yml
Labels: documentation

#207 :recycle: docs: deploy branch
  .github/workflows/aws.yml
  com.trillionares.tryit.trial/src/main/java/com/trillionares/tryit/trial/jhtest/domain/service/TrialService.java
Labels: documentation

#216 Update aws.yml
  .github/workflows/aws.yml
Labels: documentation

#218 Update aws.yml
  .github/workflows/aws.yml
Labels: documentation

#219 Update aws.yml
  .github/workflows/aws.yml
Labels: documentation

#220 Update aws.yml
  .github/workflows/aws.yml
Labels: documentation

#225 Update aws.yml
  .github/workflows/aws.yml
Labels: documentation

#226 Update aws.yml
  .github/workflows/aws.yml
Labels: documentation

#224 feat: 모집 상태 변경 스케줄링 및 Redis TTL 기반 Polling 기능 추가
  com.trillionares.tryit.product/build.gradle
  com.trillionares.tryit.product/src/main/java/com/trillionares/tryit/product/ProductApplication.java
  com.trillionares.tryit.product/src/main/java/com/trillionares/tryit/product/application/service/RecruitmentService.java
  com.trillionares.tryit.product/src/main/java/com/trillionares/tryit/product/application/service/RecruitmentStatusPoller.java
  com.trillionares.tryit.product/src/main/java/com/trillionares/tryit/product/infrastructure/config/RedisConfig.java
  com.trillionares.tryit.product/src/main/java/com/trillionares/tryit/product/infrastructure/config/SchedulerConfig.java
  com.trillionares.tryit.product/src/main/java/com/trillionares/tryit/product/infrastructure/service/RedisService.java
Labels: feature

#228 :rotating_light: bug: linked Service to Eureka
  com.trillionares.tryit.auth/src/main/resources/application.yml
  com.trillionares.tryit.config/src/main/resources/application.yml
  com.trillionares.tryit.gateway/src/main/resources/application.yml
  com.trillionares.tryit.image-manage/src/main/resources/application.yml
  com.trillionares.tryit.notification/src/main/resources/application.yml
  com.trillionares.tryit.product/src/main/resources/application.yml
  com.trillionares.tryit.review/src/main/resources/application.yml
  com.trillionares.tryit.statistics/src/main/resources/application.yml
  com.trillionares.tryit.trial/src/main/resources/application.yml
Labels: bug, documentation

#229 Update aws.yml
  .github/workflows/aws.yml
Labels: documentation

#230 Update aws.yml
  .github/workflows/aws.yml
Labels: documentation

#233 :rotating_light: bug: test deploy gateway & auth
  .github/workflows/aws.yml
  com.trillionares.tryit.auth/src/main/resources/application.yml
  com.trillionares.tryit.gateway/src/main/resources/application.yml
Labels: bug, documentation

#235 :rotating_light: bug: test deploy gateway & auth 2
  com.trillionares.tryit.auth/src/main/java/com/trillionares/tryit/auth/infrastructure/config/EcsConfig.java
Labels: bug, documentation

#236 :rotating_light: bug: test deploy gateway & auth & product
  .github/workflows/aws.yml
  com.trillionares.tryit.auth/src/main/java/com/trillionares/tryit/auth/infrastructure/config/EcsConfig.java
  com.trillionares.tryit.auth/src/main/resources/application.yml
  com.trillionares.tryit.gateway/src/main/resources/application.yml
  com.trillionares.tryit.product/src/main/resources/application.yml
Labels: bug, documentation

#237 {Deploy/test gateway auth] bug: feignclient 오류 해결 및 배포
  .github/workflows/aws.yml
  com.trillionares.tryit.auth/src/main/resources/application.yml
  com.trillionares.tryit.config/src/main/resources/application.yml
  com.trillionares.tryit.gateway/src/main/resources/application.yml
  com.trillionares.tryit.image-manage/src/main/resources/application.yml
  com.trillionares.tryit.notification/src/main/resources/application.yml
  com.trillionares.tryit.product/src/main/resources/application.yml
  com.trillionares.tryit.review/src/main/resources/application.yml
  com.trillionares.tryit.statistics/src/main/resources/application.yml
  com.trillionares.tryit.trial/src/main/resources/application.yml
Labels: bug, documentation

#238 :rotating_light: bug: feignclient bug fix & deploy
  com.trillionares.tryit.auth/src/main/resources/application.yml
  com.trillionares.tryit.image-manage/src/main/resources/application.yml
  com.trillionares.tryit.notification/src/main/resources/application.yml
  com.trillionares.tryit.product/src/main/resources/application.yml
  com.trillionares.tryit.review/src/main/resources/application.yml
  com.trillionares.tryit.statistics/src/main/resources/application.yml
  com.trillionares.tryit.trial/src/main/resources/application.yml
Labels: bug, documentation

#243 Recruitment-service zipkin 연결
  .github/workflows/aws.yml
  com.trillionares.tryit.config/src/main/resources/config-repo/recruitment-service.yml
Labels: documentation

#244 main branch에서 배포
  .github/workflows/aws.yml
Labels: documentation

#246 AuthClient 버그 수정 및 배포
  .github/workflows/aws.yml
  com.trillionares.tryit.product/src/main/java/com/trillionares/tryit/product/domain/client/AuthClient.java
Labels: bug, documentation, feature

#247 배포스크립트 병렬처리
  .github/workflows/aws.yml
Labels: documentation

#248 matrix 내 환경변수 제거
  .github/workflows/aws.yml
Labels: bug, documentation

#249 :recycles: refactor: Deployment script processing
  .github/workflows/aws.yml
Labels: documentation

#250 :recycles: refactor: Deployment script processing
  .github/workflows/aws.yml
Labels: documentation

#251 :recycles: refactor: Deployment script parallel processing
  .github/workflows/aws.yml
Labels: documentation

#252 :recycles: refactor: Deployment script parallel processing
  .github/workflows/aws.yml
Labels: bug, documentation

#253 :recycles: refactor: Deployment script parallel processing
  .github/workflows/aws.yml
Labels: documentation

#254 :recycles: refactor: Deployment script parallel processing
  .github/workflows/aws.yml
Labels: bug, documentation

#255 :recycles: refactor: Deployment script processing
  .github/workflows/aws.yml
Labels: bug, documentation

#256 [refactor/product] 상품 조회시 필드에 userid 추가
  com.trillionares.tryit.product/src/main/java/com/trillionares/tryit/product/application/service/ProductService.java
  com.trillionares.tryit.product/src/main/java/com/trillionares/tryit/product/presentation/dto/response/ProductInfoResponseDto.java
Labels: feature

#242 [Feat/review-read-statistics_data] feat: 리뷰 통계 조회
  com.trillionares.tryit.review/build.gradle
  com.trillionares.tryit.review/src/main/java/com/trillionares/tryit/review/application/dto/response/ReviewStatisticsDataResponseDto.java
  com.trillionares.tryit.review/src/main/java/com/trillionares/tryit/review/application/service/ReviewService.java
  com.trillionares.tryit.review/src/main/java/com/trillionares/tryit/review/infrastructure/persistence/ReviewQueryRepository.java
  com.trillionares.tryit.review/src/main/java/com/trillionares/tryit/review/libs/config/QuerydslConfig.java
  com.trillionares.tryit.review/src/main/java/com/trillionares/tryit/review/presentation/controller/ReviewController.java
Labels: feature

#258 :recycle: refactor: product & trial & image-manage deploy test
  .github/workflows/aws.yml
Labels: documentation

#263 :recycle: refactor: update version actions/download-artifact@v3 -> ac…
  .github/workflows/aws.yml
Labels: bug, documentation

#264 :recycle: refactor: update version actions/upload-artifact@v3 -> acti…
  .github/workflows/aws.yml
Labels: bug, documentation

#260 [ Fix/review-read-statistics_data] 리뷰 API 명세서 확인
  com.trillionares.tryit.review/src/main/java/com/trillionares/tryit/review/application/dto/response/ReviewDeleteResponseDto.java
  com.trillionares.tryit.review/src/main/java/com/trillionares/tryit/review/application/service/ReviewService.java
Labels: invalid

#265 [Fix/statistics-api-check] 통계 API 명세서 확인
  com.trillionares.tryit.statistics/src/main/java/com/trillionares/tryit/statistics/application/dto/request/StatisticsCreateRequestDto.java
  com.trillionares.tryit.statistics/src/main/java/com/trillionares/tryit/statistics/application/dto/response/StatisticsGetResponseDto.java
  com.trillionares.tryit.statistics/src/main/java/com/trillionares/tryit/statistics/application/service/StatisticsService.java
  com.trillionares.tryit.statistics/src/main/java/com/trillionares/tryit/statistics/domain/model/Statistics.java
  com.trillionares.tryit.statistics/src/main/java/com/trillionares/tryit/statistics/presentation/dto/StatisticsCreateRequest.java
Labels: invalid

#269 [develop] Redis 캐싱 메모리를 활용한 상품 조회 기능 추가
  com.trillionares.tryit.config/src/main/resources/config-repo/gateway-service.yml
  com.trillionares.tryit.product/src/main/java/com/trillionares/tryit/product/application/service/ProductService.java
  com.trillionares.tryit.product/src/main/java/com/trillionares/tryit/product/domain/repository/ProductItemRepository.java
  com.trillionares.tryit.product/src/main/java/com/trillionares/tryit/product/presentation/controller/ProductController.java
  com.trillionares.tryit.product/src/main/java/com/trillionares/tryit/product/presentation/dto/ProductInfoToProductItemDto.java
  com.trillionares.tryit.product/src/main/java/com/trillionares/tryit/product/presentation/dto/response/ProductInfoResponseDto.java
Labels: feature

#270 Update aws.yml
  .github/workflows/aws.yml
Labels: documentation

#271 커밋 누락된 파일 추가
  com.trillionares.tryit.product/src/main/java/com/trillionares/tryit/product/domain/model/product/ProductItem.java
Labels: feature

#276 :recycle: refactor: linked zipkin to gateway & authclient bug fix
  .github/workflows/aws.yml
  com.trillionares.tryit.gateway/src/main/resources/application.yml
  com.trillionares.tryit.product/src/main/java/com/trillionares/tryit/product/domain/client/AuthClient.java
Labels: feature

#275 [Feat/get search] 알림 검색 기능 추가
  com.trillionares.tryit.notification/src/main/java/com/trillionares/tryit/notification/application/dto/request/NotificationSearchRequest.java
  com.trillionares.tryit.notification/src/main/java/com/trillionares/tryit/notification/application/dto/response/NotificationResponse.java
  com.trillionares.tryit.notification/src/main/java/com/trillionares/tryit/notification/application/service/NotificationService.java
  com.trillionares.tryit.notification/src/main/java/com/trillionares/tryit/notification/domain/repository/NotificationRepositoryCustom.java
  com.trillionares.tryit.notification/src/main/java/com/trillionares/tryit/notification/domain/repository/NotificationRepositoryImpl.java
  com.trillionares.tryit.notification/src/main/java/com/trillionares/tryit/notification/infrastructure/messaging/event/SubmissionEventConsumer.java
  com.trillionares.tryit.notification/src/main/java/com/trillionares/tryit/notification/infrastructure/persistence/NotificationRepository.java
  com.trillionares.tryit.notification/src/main/java/com/trillionares/tryit/notification/libs/exception/ErrorCode.java
  com.trillionares.tryit.notification/src/main/java/com/trillionares/tryit/notification/presentation/controller/NotificationController.java
Labels: feature

#277 [Feat/statistics-create-auto] 통계 생성 자동화
  com.trillionares.tryit.statistics/src/main/java/com/trillionares/tryit/statistics/StatisticsApplication.java
  com.trillionares.tryit.statistics/src/main/java/com/trillionares/tryit/statistics/application/dto/response/StatisticsCreateDataResponseDto.java
  com.trillionares.tryit.statistics/src/main/java/com/trillionares/tryit/statistics/application/dto/response/StatisticsDataToRecruitmentResponseDto.java
  com.trillionares.tryit.statistics/src/main/java/com/trillionares/tryit/statistics/application/dto/response/StatisticsGetProductInfoResponseDto.java
  com.trillionares.tryit.statistics/src/main/java/com/trillionares/tryit/statistics/domain/client/ProductClient.java
  com.trillionares.tryit.statistics/src/main/java/com/trillionares/tryit/statistics/domain/client/ReviewClient.java
  com.trillionares.tryit.statistics/src/main/java/com/trillionares/tryit/statistics/libs/config/StatisticsScheduler.java
Labels: feature

#281 [Feat/elk] Elastic Search를 통한 상품 조회 기능 추가
  com.trillionares.tryit.gateway/build.gradle
  com.trillionares.tryit.image-manage/src/main/java/com/trillionares/tryit/image_manage/domain/service/ImageEndpoint.java
  com.trillionares.tryit.image-manage/src/main/java/com/trillionares/tryit/image_manage/presentation/dto/ProductIdAndProductImageIdDto.java
  com.trillionares.tryit.product/build.gradle
  com.trillionares.tryit.product/src/main/java/com/trillionares/tryit/product/application/service/ProductEndpoint.java
  com.trillionares.tryit.product/src/main/java/com/trillionares/tryit/product/application/service/ProductService.java
  com.trillionares.tryit.product/src/main/java/com/trillionares/tryit/product/application/service/SearchProductServiceImpl.java
  com.trillionares.tryit.product/src/main/java/com/trillionares/tryit/product/domain/model/product/SearchProduct.java
  com.trillionares.tryit.product/src/main/java/com/trillionares/tryit/product/domain/repository/ProductElasticSearchRepository.java
  com.trillionares.tryit.product/src/main/java/com/trillionares/tryit/product/infrastructure/config/ElasticConfig.java
  com.trillionares.tryit.product/src/main/java/com/trillionares/tryit/product/presentation/controller/ProductController.java
  com.trillionares.tryit.product/src/main/java/com/trillionares/tryit/product/presentation/dto/ProductIdAndProductImageIdDto.java
  com.trillionares.tryit.product/src/main/resources/application.yml
  com.trillionares.tryit.product/src/main/resources/logback-spring.xml
Labels: feature

#284 [Feat/enhanced submission] feat: 체험단 신청 API 처리량 성능 향상
  .github/workflows/aws.yml
  com.trillionares.tryit.product/src/main/java/com/trillionares/tryit/product/application/service/RecruitmentService.java
  com.trillionares.tryit.product/src/main/java/com/trillionares/tryit/product/domain/model/recruitment/RecruitmentItem.java
  com.trillionares.tryit.product/src/main/java/com/trillionares/tryit/product/domain/repository/RecruitmentItemRepository.java
  com.trillionares.tryit.product/src/main/java/com/trillionares/tryit/product/domain/repository/RecruitmentRepository.java
  com.trillionares.tryit.product/src/main/java/com/trillionares/tryit/product/presentation/dto/RecruitmentToRecruitmentItemDto.java
  com.trillionares.tryit.trial/src/main/java/com/trillionares/tryit/trial/jhtest/domain/model/Trial.java
  com.trillionares.tryit.trial/src/main/java/com/trillionares/tryit/trial/jhtest/domain/service/TrialEndpoint.java
  com.trillionares.tryit.trial/src/main/java/com/trillionares/tryit/trial/jhtest/domain/service/TrialService.java
  com.trillionares.tryit.trial/src/main/java/com/trillionares/tryit/trial/jhtest/presentation/controller/trialController.java
Labels: feature

#282 [Feat/add monitoring] grafana, prometheus 기능 추가
  .env
  .gitignore
  com.trillionares.tryit.auth/build.gradle
  com.trillionares.tryit.auth/src/main/java/com/trillionares/tryit/auth/infrastructure/config/SecurityConfig.java
  com.trillionares.tryit.config/src/main/resources/bootstrap.yml
  com.trillionares.tryit.config/src/main/resources/config-repo/application.yml
  com.trillionares.tryit.config/src/main/resources/config-repo/auth-service.yml
  com.trillionares.tryit.config/src/main/resources/config-repo/gateway-service.yml
  com.trillionares.tryit.config/src/main/resources/config-repo/image-manage-service.yml
  com.trillionares.tryit.config/src/main/resources/config-repo/notification-service.yml
  com.trillionares.tryit.config/src/main/resources/config-repo/product-service.yml
  com.trillionares.tryit.config/src/main/resources/config-repo/review-service.yml
  com.trillionares.tryit.config/src/main/resources/config-repo/statistics-service.yml
  com.trillionares.tryit.image-manage/build.gradle
  com.trillionares.tryit.notification/build.gradle
  com.trillionares.tryit.notification/src/main/generated/com/trillionares/tryit/notification/domain/common/base/QBaseEntity.java
  com.trillionares.tryit.notification/src/main/generated/com/trillionares/tryit/notification/domain/model/QNotification.java
  com.trillionares.tryit.notification/src/main/java/com/trillionares/tryit/notification/libs/exception/ErrorCode.java
  com.trillionares.tryit.notification/src/main/java/com/trillionares/tryit/notification/presentation/controller/NotificationController.java
  com.trillionares.tryit.product/build.gradle
  com.trillionares.tryit.review/build.gradle
  com.trillionares.tryit.statistics/build.gradle
  com.trillionares.tryit.trial/build.gradle
  com.trillionares.tryit.trial/src/main/resources/application.yml
  docker-compose.yml
  prometheus/prometheus.yml
Labels: feature

#285 [Feat/distributed lock] feat: 상품 재고관리시 Redisson의 분산락을 활용한 재고관리
  com.trillionares.tryit.product/build.gradle
  com.trillionares.tryit.product/src/main/java/com/trillionares/tryit/product/application/service/RecruitmentService.java
  com.trillionares.tryit.product/src/main/java/com/trillionares/tryit/product/infrastructure/config/RedissonConfig.java
Labels: feature

#286 product-service 배포
  .github/workflows/aws.yml
Labels: documentation

#287 :memo: docs: deploy gateway & trial
  .github/workflows/aws.yml
Labels: bug, documentation

#288 :rotating_light: fix: bugfix & deploy
  .github/workflows/aws.yml
  com.trillionares.tryit.config/src/main/resources/config-repo/application.yml
  com.trillionares.tryit.config/src/main/resources/config-repo/trial-service.yml
  com.trillionares.tryit.gateway/src/main/resources/application.yml
  com.trillionares.tryit.product/src/main/java/com/trillionares/tryit/product/domain/repository/RecruitmentRepository.java
Labels: bug, documentation

#289 :rotating_light: fix: test
  .github/workflows/aws.yml
  com.trillionares.tryit.product/src/main/java/com/trillionares/tryit/product/application/service/RecruitmentService.java
  com.trillionares.tryit.product/src/main/java/com/trillionares/tryit/product/presentation/controller/RecruitmentController.java
Labels: documentation, feature

#290 fix: test
  .github/workflows/aws.yml
  com.trillionares.tryit.trial/src/main/java/com/trillionares/tryit/trial/jhtest/domain/client/RecruitmentClient.java
  com.trillionares.tryit.trial/src/main/java/com/trillionares/tryit/trial/jhtest/domain/service/TrialService.java
Labels: documentation, feature

#291 :rotating_light: fix: test
  com.trillionares.tryit.trial/src/main/java/com/trillionares/tryit/trial/jhtest/domain/service/TrialService.java
Labels: feature

#292 :rotating_light: fix: test
  .github/workflows/aws.yml
  com.trillionares.tryit.product/src/main/java/com/trillionares/tryit/product/presentation/controller/RecruitmentController.java
  com.trillionares.tryit.trial/src/main/java/com/trillionares/tryit/trial/jhtest/domain/client/RecruitmentClient.java
Labels: bug, documentation, feature
